library(OIsurv)
data("tongue")
tongue$type <- as.factor(tongue$type)
gender <- sample(c("f","m"), 80, replace=TRUE)
category <- sample(c("a","b","c"), 80, replace=TRUE)
df <- as.data.frame(cbind(tongue[1:3], gender, category))